SRCS = z1.go Switch.go  Train.go Line.go Order.go Enums.go Data.go ConstructionCrew.go BreakdownGenerator.go Pair.go Functions.go Worker.go WorkerManager.go Notification.go
PROGRAM = z1

$(PROGRAM):  $(SRCS)
	go build $(SRCS) 